modLoader="javafml"
loaderVersion="[37,)"
license="Public Domain"

[[mods]]
modId="meatcraft"
version="0.2.3"
displayName="Meatcraft"
credits="Pengull, NovisRail"
displayURL="https://github.com/RealPengull/Meatcraft"
authors="Pengull, NovisRail"
description='''
A modpack used for testing.
'''

[[dependencies.meatcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




