modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"

[[mods]]
modId="meatcraft"
version="0.2.5"
displayName="Meatcraft"
credits="Pengull, NovisRail"
displayURL="https://github.com/RealPengull/Meatcraft"
logoFile="logo.png"
authors="Pengull, NovisRail"
description='''
A cursed modpack with dank memes and CUM.
'''

[[dependencies.meatcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




